apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{.Chart.Name}}-{{ .Release.Name }}-ingress"
  namespace: "{{.Values.namespace}}"
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
spec:
  tls:
  - hosts:
    - "{{.Chart.Name}}.{{ .Values.ingressDomain }}"
    secretName: {{ .Values.ingressSecretName }}
  rules:
  - host: "{{.Chart.Name}}.{{ .Values.ingressDomain }}"
    http:
      paths:
      - path: /
        backend:
          service:
            name: "{{.Chart.Name}}-{{ .Release.Name }}"
            port:
              number: {{ .Values.port }}
