apiVersion: v1
kind: Service
metadata:
  name: "{{.Chart.Name}}-{{ .Release.Name }}-service"
  namespace: "{{.Values.namespace}}"
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
spec:
  type: NodePort
  # loadBalancerIP: {{ .Values.loadBalancerIP }}
  selector:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
