apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-{{ .Release.Name }}-configmap"
  namespace: {{.Values.namespace}}
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
data:
  allowed: '"true"'
