apiVersion: v1
kind: Secret
metadata:
  name: "{{.Chart.Name}}-{{ .Release.Name }}-secret"
  namespace: "{{.Values.namespace}}"
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
type: Opaque
stringData:
  username: admin
  password: admin@example
